name: mlhc-project
channels:
  - conda-forge
  - defaults
dependencies:
  # Python
  - python>=3.9

  # Core data processing
  - pandas>=1.5.0
  - numpy>=1.24.0

  # Database
  - pip

  # Testing
  - pytest>=7.0.0

  # Machine Learning
  - pytorch>=2.0.0
  - scikit-learn>=1.3.0

  # Visualization
  - matplotlib>=3.7.0

  # Pip dependencies (not available in conda)
  - pip:
    - duckdb>=0.9.0
    - google-api-python-client>=2.100.0
    - google-auth-httplib2>=0.1.0
    - google-auth-oauthlib>=1.0.0
    - google-cloud-bigquery>=3.11.0