

WINDOW_HOURS: int = 48
GAP_HOURS: int = 6
MIN_LOS_HOURS: int = 54
MIN_AGE: int = 18
MAX_AGE: int = 89

PROLONGED_LOS_THRESHOLD_DAYS: int = 7
READMISSION_WINDOW_DAYS: int = 30
MORTALITY_WINDOW_DAYS: int = 30

SECONDS_PER_HOUR = 60 * 60
SECONDS_PER_YEAR = 365 * 24 * SECONDS_PER_HOUR
