

# Windows / thresholds (first 48h window, 6h gap, etc.)
WINDOW_HOURS: int = 48
GAP_HOURS: int = 6
MIN_LOS_HOURS: int = 54
MIN_AGE: int = 18
MAX_AGE: int = 89

# Target windows
PROLONGED_LOS_THRESHOLD_DAYS: int = 7
READMISSION_WINDOW_DAYS: int = 30
MORTALITY_WINDOW_DAYS: int = 30

SECONDS_PER_HOUR = 60 * 60
SECONDS_PER_YEAR = 365 * 24 * SECONDS_PER_HOUR


# Categorical vocabularies
ADMISSION_TYPE = {
    "EMERGENCY", "URGENT", "ELECTIVE",
}
ADMISSION_LOCATION = {
    "EMERGENCY ROOM ADMIT", "TRANSFER FROM HOSP/EXTRAM",
    "TRANSFER FROM OTHER HEALT", "CLINIC REFERRAL/PREMATURE",
    "** INFO NOT AVAILABLE **", "TRANSFER FROM SKILLED NUR",
    "TRSF WITHIN THIS FACILITY", "HMO REFERRAL/SICK",
    "PHYS REFERRAL/NORMAL DELI",
}
INSURANCE = {"MEDICARE", "PRIVATE", "MEDICAID", "GOVERNMENT", "SELF_PAY"}
LANGUAGE = {"ENGL","SPAN","RUSS","CANT","PORT","MAND","HAIT","FREN","GREE","ITAL","CAPE","VIET","ARAB"}
RELIGION = {
    "CATHOLIC","NOT_SPECIFIED","UNOBTAINABLE","PROTESTANT_QUAKER","JEWISH","OTHER",
    "CHRISTIAN_SCIENTIST","BUDDHIST","MUSLIM","JEHOVAHS_WITNESS","GREEK_ORTHODOX",
    "HINDU","UNITARIAN_UNIVERSALIST","SEVENTH_DAY_ADVENTIST","ROMANIAN_EAST_ORTH",
    "BAPTIST","EPISCOPALIAN","LUTHERAN","METHODIST","HEBREW",
}
MARTIAL_STATUS = {
    "MARRIED","SINGLE","WIDOWED","DIVORCED","SEPARATED",
    "UNKNOWN_NOT_SPECIFIED","LIVING_WITH_PARTNER",
}
ETHNICITY = {
    "WHITE","BLACK_AFRICAN_AMERICAN","UNKNOWN_NOT_SPECIFIED","HISPANIC_OR_LATINO",
    "ASIAN","UNABLE_TO_OBTAIN","PATIENT_DECLINED_TO_ANSWER","OTHER","ASIAN_CHINESE",
    "HISPANIC_LATINO_PUERTO_RICAN","BLACK_CAPE_VERDEAN","WHITE_RUSSIAN","MULTI_RACE_ETHNICITY",
    "BLACK_HAITIAN","ASIAN_VIETNAMESE","ASIAN_CAMBODIAN","WHITE_EASTERN_EUROPEAN",
    "ASIAN_FILIPINO","HISPANIC_LATINO_DOMINICAN","WHITE_OTHER_EUROPEAN","PORTUGUESE",
    "BLACK_AFRICAN","MIDDLE_EASTERN","ASIAN_INDIAN","HISPANIC_LATINO_GUATEMALAN",
    "ASIAN_ASIAN_INDIAN","HISPANIC_LATINO_CUBAN","AMERICAN_INDIAN_ALASKA_NATIVE",
    "HISPANIC_LATINO_SALVADORAN","NATIVE_HAWAIIAN_OR_OTHER_PACIFIC_ISLANDER",
    "ASIAN_KOREAN","CARIBBEAN_ISLAND","SOUTH_AMERICAN",
}
